version: '3.8'

services:
  backend-python:
    build: ./src/backend-python
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/dbname

  backend-go:
    build: ./src/backend-go
    ports:
      - "8080:8080"

  simulation:
    build: ./src/simulation
    volumes:
      - ./src/simulation:/app

  analytics:
    build: ./src/analytics

  frontend:
    build: ./src/frontend
    ports:
      - "3000:3000"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
